### ISSUE TITLE
Feature Request: Macro Complete Sound

### ISSUE THREAD

**Issue by mindofbeholder** [alostsock/craftingway#2]
I've been spoiled by ffxivteamcraft.

Can you add a toggle to play a sound effect when a macro completes?
ffxivteamcraft example:
/echo Craft finished <se.1>

**Comment by alostsock** [comment]
Thanks for making this an issue, much easier to track.

This is actually already implemented, but only if a rotation spills over into two parts (>15 steps).

I can add this for when a rotation is 14 steps or under, but if the macro is exactly 15 steps, should it still play a sound? Otherwise it will get split into two parts if the `/echo` is added.

**Comment by mindofbeholder** [comment]
Not a problem! I personally prefer to use issues when a project is github hosted :)

I'm using ffxivteamcraft as a reference point.

Their current behavior is that if the macro is 15 steps they drop the end sound, even if enabled.
If the macro is 16 steps they add the end sound back in and take the last two steps and push them into a second macro with the sound also enabled.

**Comment by alostsock** [comment]
Should be fixed by https://github.com/alostsock/craftingway/commit/6a9c77fc6c475fe1f9e5eea833bfda2a1227ee5e
