### ISSUE TITLE
Addition of HQ Items (today?) Decreases Overall Quality of App

### ISSUE THREAD

**Issue by KKaminski93** [alostsock/craftingway#34]
Was there a different build up yesterday? I noticed a few undesirables today...

- App now runs generally slower to find a recipe
- App produces longer recipes now (in terms of number of steps) and also they yield less quality overall in the finished product

I think the addition of the HQ items made the app slower, less no-frills and the app is literally slower and produces worse results now. Can you point me to a commit of the build that was up yesterday so I can host my own copy please?

Also, your Discord is refusing to let me join? So I had to post this all here.

**Comment by alostsock** [comment]
I unfortunately haven't had the time to touch this project at all in the past few weeks, so nothing has changed since [my last commit](https://github.com/alostsock/craftingway/commit/fe7e50dceab8bea2eb6636c86c5e33da49a11abe) on the 2nd of this month.

The HQ ingredients feature has been in the app for [over ~1 year now](https://github.com/search?q=repo%3Aalostsock%2Fcraftingway+ingredients&type=commits), which makes it hard for me to pin down the behavior that you're seeing.

There are a few things that I can think of to do as a sanity check:
1. The solver is completely RNG-based, and while the results should be relatively reliable, sometimes it takes a few more tries to get a better rotation out of it.
2. Like you, I often find the solver does better when disabling HQ ingredients. After running the solver, the ingredients can be re-enabled to see the boost in quality. This is especially useful when reaching 100% quality is difficult; the solver becomes less optimistic when faced with a greater quality target, so tries to incorporate better quality moves during the solve. Sometimes this does result in slightly longer solves (maybe a few extra seconds), but nothing drastically longer.
3. You could double check that the `Rev ######` text on the bottom right of the page matches the current commit hash (currently `fe7e50`). This means you're on the latest version of the page, which would rule out any weirdness due to browser/cdn caching.

You can try the development steps written out in the [README ](https://github.com/alostsock/craftingway?tab=readme-ov-file#development) if you want to run this on your own. I'd be willing to help further via Discord, but I'm not sure why you're not able to join (I just tried the invite link with a fresh account, and that seemed to work).

**Comment by alostsock** [comment]
Closing this due to lack of followup.
